version: '3.4'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports: 
     - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wp_database
      - MYSQL_USER=wp_user
      - MYSQL_PASSWORD=wp_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-network

  phpmyadmin:
    image: phpmyadmin
    ports: 
     - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - backend-network
      - frontend-network

  wordpress:
    image: wordpress
    ports: 
     - 80:80
    environment:
      - WORDPRESS_DB_NAME=wp_database
      - WORDPRESS_DB_USER=wp_user
      - WORDPRESS_DB_PASSWORD=wp_password
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - backend-network
      - frontend-network

volumes:
 mysql_data:
 wordpress_data:

networks:
  backend-network:
  frontend-network:
